---
- name: Copy 'is_cluster_ready' file
  copy: dest=/bin/is_cluster_ready src=is_cluster_ready mode=0755 force=no

- name: Set hostname
  command: hostname sgemaster

# Manage the /etc/hosts file
- shell: |
    for i in `seq 1 {{NNODES}}`; do
      item="vnode${i}";
      grep -q "\<${item}\>" /etc/hosts || echo "127.0.0.1 ${item}.localdomain ${item}" >> /etc/hosts;
    done

# SGE configuration Specific tasks
- command: qconf -as sgemaster

- copy:
    content: |
       hostname vnode{{item}}.localdomain
       {{NODE_DEF}}
    dest: /tmp/vnode{{item}}.def
  with_sequence: start=1 end={{NNODES}}

- shell: qconf -se vnode{{item}} || qconf -Ae /tmp/vnode{{item}}.def
  with_sequence: start=1 end={{NNODES}}

- shell: qconf -ah vnode{{item}}
  with_sequence: start=1 end={{NNODES}}

- copy: content="{{ALL_Q_CONF}}" dest=/tmp/all.q
- copy:
    content: |
       group_name @allhosts
       hostlist {% for number in range(1, NNODES|int + 1) %} vnode{{number}} {% endfor %}
    dest: /tmp/allhosts.hgrp

- shell: qconf -shgrp @allhosts || qconf -Ahgrp /tmp/allhosts.hgrp
- shell: qconf -sq all.q || qconf -Aq /tmp/all.q
